ZDOTDIR=$HOME/.config/zsh

export HISTFILE=~/.cache/zsh/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS


export PATH="${PATH}:$HOME/bin"
export EDITOR="nvim"
export VISUAL="nvim"
